### ISSUE TITLE
echo quickfix/location entrie description in command line.

### ISSUE THREAD

**Issue by mulianov** [tomtom/quickfixsigns_vim#53]
Could you please add such feature?
Echo quickfix/location entries description in command line when cursor point to it.

**Comment by tomtom** [comment]
Using :echo may have the unpleasant consequence that users are queried to press Enter. Unfortunately, when trying to implement similar functionality for other plugins, it seems it isn't 100% possible to always avoid this.

Anyway, IMHO such a functionality should be implemented in a plugin of its own, which wouldn't be too difficult. On CursorHold(I) events, you'd have to call a function that retrieves the lists via getqflist() and getloclist() and uses filter to get only the items for the current line.
