### ISSUE TITLE
Colorschemes for QuickfixSigns defined in color files is overridden by autoloader

### ISSUE THREAD

**Issue by jfelchner** [tomtom/quickfixsigns_vim#59]
If a colorscheme as a definition for the highlight name defined in the autoloader, quickfixsigns overwrites them when it is autoloaded.  I'm assuming it happens [here](https://github.com/tomtom/quickfixsigns_vim/blob/master/autoload/quickfixsigns/vcsdiff.vim#L98-L102)

**Comment by tomtom** [comment]
In case it is acceptable to set a variable, the previous commit should 
hopefully solve this problem.

**Comment by jfelchner** [comment]
@tomtom that's perfect!  Thanks!
