### ISSUE TITLE
Disable on specific buffer type

### ISSUE THREAD

**Issue by simonweil** [tomtom/quickfixsigns_vim#61]
Thank you for a useful plugin!
Is it possible to disable the plugin on a specific buffer type or file type?

**Comment by tomtom** [comment]
> Is it possible to disable the plugin on a specific buffer type or file 
> type?
>
This are your buffer-local options:

:h QuickfixsignsSet

" If the buffer-local variable b:quickfixsigns_ignore (a list of
" strings) exists, sign classes in that list won't be displayed for the
" current buffer.

:h :QuickfixsignsDisable

You can use :autocmd Filetype to disable qfs for certain filetypes.

You can also use g:quickfixsigns_blacklist_buffer to blacklist buffers 
based on their name.

HTH
