### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by vat-sqor** [tomtom/quickfixsigns_vim#64]
Hi @tomtom . Is this repo maintained? if not, I'll file a PR to mark it as unmaintained. 

Thanks!

**Comment by tomtom** [comment]
It is maintained in the sense that I'll fix issues I can track down. I won't test interactions with other plugins if users don't provide sufficient info etc.

**Comment by tomtom** [comment]
BTW if you're willing to invest time in free software (generally speaking), you might want to consider help fixing issues instead of filing such PRs.
